import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import axios from "axios";
import { useEffect, useState } from "react";
import { BsSearch } from "react-icons/bs";
import cloudyBG from "../images/cloudybg.jpg";
import Weather from "@/components/Weather";
import LoadingBar from "@/components/LoadingBar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [city, setCity] = useState("");
  const [weather, setWeather] = useState({});
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    console.log(loading);
  }, [loading]);

  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&units=metric&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}`;

  const fetchWeather = async (e) => {
    e.preventDefault();
    setLoading(true);
    await axios.get(url).then((res) => {
      setWeather(res.data);
    });
    setCity("");
    setLoading(false);
  };
  return (
    <div
      style={{ width: "100vw", height: "100vh", position: "absolute" }}
      className="font-Lexend"
    >
      <Head>
        <title>Weather Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Lexend:wght@300&display=swap"
          rel="stylesheet"
        />
      </Head>

      <Image
        fill
        src={cloudyBG}
        alt="cbg_001"
        className="object-cover relative min-w-[100vw] min-h-[100vh]"
      />
      <div className="absolute top-0 left-0 right-0 bottom-0 bg-black/20" />

      {/* Search */}
      <div className="relative flex bg-black/40 rounded-2xl justify-between items-center max-w-[400px] w-full m-auto text-white z-10 mt-5 shadow-2xl">
        <form
          onSubmit={fetchWeather}
          className="flex justify-between items-center w-full m-auto p-3 text-white rounded-2xl"
        >
          <div>
            <input
              onChange={(e) => {
                setCity(e.target.value);
              }}
              className="bg-transparent border-none text-white/90 focus:outline-none text-2xl placeholder-white/90"
              type="text"
              placeholder="Search a City"
            />
          </div>
          <button onClick={fetchWeather}>
            <BsSearch size={20} />
          </button>
        </form>
      </div>

      {/* Weather */}
      {loading && <LoadingBar />}
      {weather.main && !loading && <Weather data={weather} />}
    </div>
  );
}
